import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-covid',
  templateUrl: './covid.component.html',
  styleUrls: ['./covid.component.css']
})
export class CovidComponent implements OnInit {

  covidData = [
    {
      active: "425122",
      confirmed: "1239693",
      deaths: "29890",
      deltaconfirmed: "9",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "23/07/2020 09:52:01",
      migratedother: "414",
      recovered: "784267",
      state: "Total",
      statecode: "TT",
      statenotes: ""
    },
    {
      active: "136980",
      confirmed: "337607",
      deaths: "12556",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 21:57:05",
      migratedother: "302",
      recovered: "187769",
      state: "Maharashtra",
      statecode: "MH",
      statenotes: "302 cases are marked as non-covid deaths in MH bulletin. These have been reduced from active count [June 16] : 1328 deceased cases have been retroactively added to MH bulletin. [June 20]: 69 deceased cases have been reduced based on state bulletin. "
    },
    {
      active: "51765",
      confirmed: "186492",
      deaths: "3144",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 19:17:00",
      migratedother: "0",
      recovered: "131583",
      state: "Tamil Nadu",
      statecode: "TN",
      statenotes: "[July 22]: 444 backdated deceased entries added to Chennai in TN bulletin. 2 deaths cross notified to other states from Chennai and Coimbatore. 1 patient died after turning negative for infection in Chengalpattu. These cases have been added to TN deceased tally"
    },
    {
      active: "14954",
      confirmed: "126323",
      deaths: "3719",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 18:52:59",
      migratedother: "0",
      recovered: "107650",
      state: "Delhi",
      statecode: "DL",
      statenotes: "[July 14]: Value for the total tests conducted has been reduced by 97008 in the state bulletin. Reason given : Reconciled with ICMR figures"
    },
    {
      active: "11916",
      confirmed: "51485",
      deaths: "2228",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "23/07/2020 02:17:03",
      migratedother: "0",
      recovered: "37341",
      state: "Gujarat",
      statecode: "GJ",
      statenotes: ""
    },
    {
      active: "47066",
      confirmed: "75833",
      deaths: "1519",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 21:57:09",
      migratedother: "9",
      recovered: "27239",
      state: "Karnataka",
      statecode: "KA",
      statenotes: "9 cases are classified as non-covid related deaths in KA bulletin. They have been reduced from active cases"
    },
    {
      active: "20825",
      confirmed: "55588",
      deaths: "1263",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 21:57:12",
      migratedother: "0",
      recovered: "33500",
      state: "Uttar Pradesh",
      statecode: "UP",
      statenotes: ""
    },
    {
      active: "11155",
      confirmed: "49259",
      deaths: "438",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 22:18:06",
      migratedother: "0",
      recovered: "37666",
      state: "Telangana",
      statecode: "TG",
      statenotes: ""
    },
    {
      active: "31763",
      confirmed: "64713",
      deaths: "823",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 17:55:12",
      migratedother: "0",
      recovered: "32127",
      state: "Andhra Pradesh",
      statecode: "AP",
      statenotes: "Total includes patients from other states and a new category "
    },
    {
      active: "18450",
      confirmed: "49321",
      deaths: "1221",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 20:09:05",
      migratedother: "0",
      recovered: "29650",
      state: "West Bengal",
      statecode: "WB",
      statenotes: ""
    },
    {
      active: "8387",
      confirmed: "32334",
      deaths: "583",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 22:18:09",
      migratedother: "0",
      recovered: "23364",
      state: "Rajasthan",
      statecode: "RJ",
      statenotes: ""
    },
    {
      active: "6117",
      confirmed: "28186",
      deaths: "372",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 20:09:07",
      migratedother: "0",
      recovered: "21697",
      state: "Haryana",
      statecode: "HR",
      statenotes: ""
    },
    {
      active: "9981",
      confirmed: "30066",
      deaths: "208",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 19:17:05",
      migratedother: "1",
      recovered: "19876",
      state: "Bihar",
      statecode: "BR",
      statenotes: ""
    },
    {
      active: "7236",
      confirmed: "24842",
      deaths: "770",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 19:44:58",
      migratedother: "0",
      recovered: "16836",
      state: "Madhya Pradesh",
      statecode: "MP",
      statenotes: ""
    },
    {
      active: "8325",
      confirmed: "27745",
      deaths: "66",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "23/07/2020 00:40:07",
      migratedother: "3",
      recovered: "19351",
      state: "Assam",
      statecode: "AS",
      statenotes: "Includes one case from Nagaland. Total of 3 patients who migrated to other states has been reduced from Active count"
    },
    {
      active: "5946",
      confirmed: "19835",
      deaths: "139",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 19:45:00",
      migratedother: "0",
      recovered: "13750",
      state: "Odisha",
      statecode: "OR",
      statenotes: "[July 12th] 20 non-covid deaths reported in state dashboard are included in the deceased count [June 22nd]: NDRF/ODRF cases have been redistributed to districts based on state dashboard"
    },
    {
      active: "6831",
      confirmed: "15711",
      deaths: "273",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 20:09:10",
      migratedother: "0",
      recovered: "8607",
      state: "Jammu and Kashmir",
      statecode: "JK",
      statenotes: ""
    },
    {
      active: "3391",
      confirmed: "11301",
      deaths: "269",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 21:57:19",
      migratedother: "0",
      recovered: "7641",
      state: "Punjab",
      statecode: "PB",
      statenotes: ""
    },
    {
      active: "8821",
      confirmed: "15033",
      deaths: "46",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "23/07/2020 07:51:54",
      migratedother: "4",
      recovered: "6162",
      state: "Kerala",
      statecode: "KL",
      statenotes: "Mahe native who expired in Kannur included in Kerala's tally. One patient who absconded from Palakkad to TN and one patient who returned back to Maharashtra has been reduced from active count"
    },
    {
      active: "1740",
      confirmed: "5999",
      deaths: "29",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 23:08:12",
      migratedother: "0",
      recovered: "4230",
      state: "Chhattisgarh",
      statecode: "CT",
      statenotes: ""
    },
    {
      active: "3570",
      confirmed: "6682",
      deaths: "64",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 23:07:08",
      migratedother: "0",
      recovered: "3048",
      state: "Jharkhand",
      statecode: "JH",
      statenotes: ""
    },
    {
      active: "1856",
      confirmed: "5300",
      deaths: "57",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 23:07:10",
      migratedother: "38",
      recovered: "3349",
      state: "Uttarakhand",
      statecode: "UT",
      statenotes: "38 Migrated cases reduced from Active count"
    },
    {
      active: "1607",
      confirmed: "4176",
      deaths: "28",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 21:57:24",
      migratedother: "0",
      recovered: "2541",
      state: "Goa",
      statecode: "GA",
      statenotes: ""
    },
    {
      active: "0",
      confirmed: "0",
      deaths: "0",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "19/07/2020 09:40:01",
      migratedother: "0",
      recovered: "0",
      state: "State Unassigned",
      statecode: "UN",
      statenotes: "MoHFW website reports that these are the 'cases that are being reassigned to states'. "
    },
    {
      active: "1411",
      confirmed: "3471",
      deaths: "9",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "23/07/2020 01:06:58",
      migratedother: "18",
      recovered: "2033",
      state: "Tripura",
      statecode: "TR",
      statenotes: "18 cases are marked as migrated in Tripura dashboard."
    },
    {
      active: "642",
      confirmed: "2060",
      deaths: "0",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 19:45:02",
      migratedother: "0",
      recovered: "1418",
      state: "Manipur",
      statecode: "MN",
      statenotes: ""
    },
    {
      active: "900",
      confirmed: "2300",
      deaths: "31",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 11:17:07",
      migratedother: "0",
      recovered: "1369",
      state: "Puducherry",
      statecode: "PY",
      statenotes: ""
    },
    {
      active: "594",
      confirmed: "1725",
      deaths: "11",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 22:18:13",
      migratedother: "15",
      recovered: "1105",
      state: "Himachal Pradesh",
      statecode: "HP",
      statenotes: "HP has 16 Migrated cases which are reduced from Active #. Also, death of Tibetan refugee is included in deceased numbers, but not in confirmed"
    },
    {
      active: "186",
      confirmed: "1206",
      deaths: "2",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "21/07/2020 18:15:50",
      migratedother: "0",
      recovered: "1018",
      state: "Ladakh",
      statecode: "LA",
      statenotes: ""
    },
    {
      active: "598",
      confirmed: "1084",
      deaths: "0",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 22:39:05",
      migratedother: "0",
      recovered: "486",
      state: "Nagaland",
      statecode: "NL",
      statenotes: ""
    },
    {
      active: "241",
      confirmed: "780",
      deaths: "13",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 19:17:13",
      migratedother: "0",
      recovered: "526",
      state: "Chandigarh",
      statecode: "CH",
      statenotes: ""
    },
    {
      active: "273",
      confirmed: "775",
      deaths: "2",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 21:57:27",
      migratedother: "10",
      recovered: "490",
      state: "Dadra and Nagar Haveli and Daman and Diu",
      statecode: "DN",
      statenotes: "10 Migrated cases reduced from Active count"
    },
    {
      active: "632",
      confirmed: "949",
      deaths: "3",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "23/07/2020 00:28:06",
      migratedother: "0",
      recovered: "314",
      state: "Arunachal Pradesh",
      statecode: "AR",
      statenotes: ""
    },
    {
      active: "433",
      confirmed: "514",
      deaths: "4",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 13:17:05",
      migratedother: "0",
      recovered: "77",
      state: "Meghalaya",
      statecode: "ML",
      statenotes: "[June 17]: One case was identified to be false positive and has been removed from the confirmed cases by ML authorities."
    },
    {
      active: "147",
      confirmed: "326",
      deaths: "0",
      deltaconfirmed: "9",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "23/07/2020 09:52:05",
      migratedother: "0",
      recovered: "179",
      state: "Mizoram",
      statecode: "MZ",
      statenotes: ""
    },
    {
      active: "57",
      confirmed: "221",
      deaths: "0",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 22:18:16",
      migratedother: "1",
      recovered: "163",
      state: "Andaman and Nicobar Islands",
      statecode: "AN",
      statenotes: ""
    },
    {
      active: "326",
      confirmed: "451",
      deaths: "0",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "22/07/2020 22:18:19",
      migratedother: "13",
      recovered: "112",
      state: "Sikkim",
      statecode: "SK",
      statenotes: "13 Migrated cases reduced from Active count"
    },
    {
      active: "0",
      confirmed: "0",
      deaths: "0",
      deltaconfirmed: "0",
      deltadeaths: "0",
      deltarecovered: "0",
      lastupdatedtime: "26/03/2020 07:19:29",
      migratedother: "0",
      recovered: "0",
      state: "Lakshadweep",
      statecode: "LD",
      statenotes: ""
    }
  ]

  constructor() { }

  ngOnInit(): void {
  }

}
